### ISSUE TITLE
Please don't put AppImage into zip file

### ISSUE THREAD

**Issue by probonopd** [ktmouk/hackaru-desktop#6]
Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake, thanks.

**Comment by ktmouk** [comment]
Hi, @probonopd .
Thank you for report this issue! I will fix it as soon as possible.

**Comment by ktmouk** [comment]
#8

**Comment by probonopd** [comment]
Getting 
```
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
```

Reference:
https://github.com/electron-userland/electron-builder/issues/2597

**Comment by ktmouk** [comment]
Hmm, I checked this issue in some distributions (Ubuntu18.04, Xubuntu 18.04.2).
But both distributions work fine.
Would you tell me your Linux distribution or how to occur this error?
Thanks.

**Comment by probonopd** [comment]
Ubuntu 16.04.

**Comment by ktmouk** [comment]
OK, I removed `libsecret-1.so.0`, which is installed by default. And I could see this error.

![a](https://user-images.githubusercontent.com/17381979/56007875-2e0fe200-5d15-11e9-8d06-e397caf694d7.png)

Probably, I will be able to fix this error by using [extraFiles](https://www.electron.build/configuration/contents#extrafiles). (Copy `libsecret-1.so.0`  to `/tmp/.mount-XXXXX/usr/lib`)

However, I'm not sure this solution works fine in all distributions.
node-keytar does not work on distributions that do not have gnome-keyring or ksecretservice.

All things considered, When this error occurs, I would like you to install libsecret yourself.
This solution is not perfect but it is simple.

If you know other solutions, please let me know. Thank you for report this issue.

**Comment by probonopd** [comment]
Thank you very much. Please ping me once a release containing the fix is available for download, so that I can re-run the test.
